#!/usr/bin/env bash

# script/console: Launch a console for the application. Optionally allow an
#                 environment to be passed in to let the script handle the
#                 specific requirements for connecting to a console for that
#                 environment.

set -e

cd "$(dirname "$0")/.."

if [ -n "$1" ]; then
  case "$1" in
    production )  echo "Coonect to production console"                            ;;
    staging )     echo "Coonect to production console"                            ;;
    *)            echo "Sorry, I don't know to connect to the '$1' environment"; exit 1   ;;
  esac
else
  # no argument provided, so just run the local console in the development
  # environment. Ensure the application is up to date first.
  script/update
  exec script/run bash

fi
