#!/usr/bin/env bash

# script/rebuild: Rebuilds all docker images.

set -e

cd "$(dirname "$0")/.."

case $1 in
  js) script/run npm install
      script/run npm run build:js
      [ -d node_modules ] && rm -rf node_modules
  ;;
  *)
    script/teardown > /dev/null 2>&1 || true
    script/compose build
    script/run npm install
  ;;
esac