#!/usr/bin/env bash

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.
# This is also useful for ensuring that your bootstrapping actually works well.

set -e

cd "$(dirname "$0")/.."
script/bootstrap

# Migrate the database here
